### ISSUE TITLE
Долгий ответ сервера

### ISSUE THREAD

**Issue by VolkAlex** [PHPTCloud/IsDayOff#2]
Спасибо за труды, однако попробовав библиотеку обнаружил, что ответ составляет около 3 секунд (пробовал вызывать для одной недели) к сожалению это неприемлимо. Вот приблизительно как я это делал:

```
//configure dayOffService
$dayOffClient = new IsDayOff();
$filters = new FiltersCollection();
$filter = self::IS_DAY_OF_COUNTRY_FILTERS[$this->countryId] ?? self::IS_DAY_OF_DEFAULT_FILTER;
$filters->addOne(new $filter());
$dateTime = new \DateTime();

foreach ($data as $timeDay => $rowsData) {
  $dataHead['isDayOff'][$timeDay] = $dayOffClient->date()->isDayOff($dateTime->setTimestamp($timeDay));
}
```

**Comment by PHPTCloud** [comment]
Здравствуйте,
Скорость работы сервиса могла снизиться когда сервис переезжал на другой хостинг. Об этом писал владелец сервиса у себя в телеграм канале. Если у вас до сих запрос работает медленно, вы можете найти его контакты на офф сайте.
