### ISSUE TITLE
Update required guzzlehttp/guzzle version to ^7.0

### ISSUE THREAD

**Issue by lebedevsergey** [PHPTCloud/IsDayOff#3]
The library requires outdated guzzlehttp/guzzle of outdated ^6.0 version though the current guzzlehttp/guzzle version is 7.5.0.
It would be nice to update the required guzzlehttp/guzzle version to ^7.0

**Comment by PHPTCloud** [comment]
https://github.com/PHPTCloud/IsDayOff/commit/2e7f62f8a4deb097bf6741ac3290fb9b4658f261
