### ISSUE TITLE
Ошибки после обновления до v1.0.1 на версиях php<7.4

### ISSUE THREAD

**Issue by alnidok** [PHPTCloud/IsDayOff#6]
Версия 1.0.1 предполагает использование типизированных свойств в классах ([например](https://github.com/alnidok/IsDayOff/commit/b9f1a13dcafcc435cbda16698cb29bf373dd1644#diff-2dce8ec1e25a9b5fac98506be7e47442ca96dbe609c39473041ae5de3fa2a55eR18)), поддержка которых появилась в php7.4 - https://www.php.net/manual/ru/migration74.new-features.php#migration74.new-features.core.typed-properties.

Т.к. сейчас в composer.json нет ограничения на версию, значит после **минорного** обновления composer-пакета все, у кого версия php ниже, получат ошибки!
> syntax error, unexpected 'DateService' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

Собственно это начало происходить после того, как на https://packagist.org/packages/phptcloud/isdayoff-sdk версия пакета обновилась до 1.0.1 (2022-03-21 03:26 UTC), странно почему до сих пор не было issue :)

На будущее:
1) Изменения, ломающие обратную совместимость (в т.ч. переход на новые версии языка) должны происходить в мажорных версиях пакета, тогда стандартный `"phptcloud/isdayoff-sdk": "^1.0"`, не будет обновлять до версий 2.0 и т.д. ([подробнее](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)).
2) Всегда указывать версию языка и все зависимости, необходимые для работы пакета, в composer.json (секция require). Тогда composer будет ругаться при попытке обновить пакет, если что-то не так. А сейчас все успешно установится, и о проблеме станет известно лишь по ParseError.

**Comment by PHPTCloud** [comment]
Спасибо за обратную связь. Вынесу изменения с типизацией и требованиями к версии языка в версию 2.0.0 в ближайшее время.

**Comment by PHPTCloud** [comment]
Решено https://github.com/PHPTCloud/is-day-off/pull/7
